from typing import Protocol


class DeepTutorAdapter(Protocol):
    def ask_document(self, *, kb_id: str, question: str, language: str) -> dict: ...
    def generate_quiz(self, payload: dict) -> dict: ...
    def grade_quiz(self, payload: dict) -> dict: ...


class HermesAdapter(Protocol):
    def run_daily_checkin(self, snapshot: dict) -> dict: ...
    def run_weekly_review(self, snapshot: dict) -> dict: ...
    def run_plan_rebalance(self, snapshot: dict, instruction: str) -> dict: ...


class RouterAdapter(Protocol):
    def health_check(self) -> dict: ...
