from typing import Protocol


class DeepTutorAdapter(Protocol):
    def health_check(self) -> dict: ...
    def create_or_get_kb(self, track: dict) -> dict: ...
    def upload_document(self, *, track_id: str, kb_id: str, file_path: str, title: str) -> dict: ...
    def ask_document(self, *, kb_id: str, question: str, language: str) -> dict: ...
    def generate_quiz(self, payload: dict) -> dict: ...
    def grade_quiz(self, payload: dict) -> dict: ...


class HermesAdapter(Protocol):
    def run_daily_checkin(self, snapshot: dict) -> dict: ...
    def run_weekly_review(self, snapshot: dict) -> dict: ...
    def run_plan_rebalance(self, snapshot: dict, instruction: str) -> dict: ...


class RouterAdapter(Protocol):
    def health_check(self) -> dict: ...
    def list_models(self) -> dict: ...
    def list_model_groups(self) -> dict: ...
    def create_chat_completion(
        self,
        *,
        model: str,
        messages: list[dict],
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> dict: ...
